import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import LayoutContainer from "./components/ui/layout-container";

const recursive = localFont({
  src: [
    { path: "./fonts/Recursive_Regular.woff2", weight: "400", style: "normal" },
    {
      path: "./fonts/Recursive_bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <LayoutContainer>{children}</LayoutContainer>
      </body>
    </html>
  );
}
