import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

const recursive = localFont({
  src: [
    { path: "./fonts/Recursive_Regular.woff2", weight: "400", style: "normal" },
    {
      path: "./fonts/Recursive_bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${recursive.className}`}>
        <div className="flex flex-col min-h-screen">{children}</div>
      </body>
    </html>
  );
}
